[package]
name = "glutin-skeleton"
version = "0.1.0"
authors = ["Benjamin Lindley <benjameslindley@gmail.com>"]
edition = "2018"

[dependencies]
glutin = "0.19"
gl = "*"
cgmath = "0.16"
image = "0.21"

multitext = {git = "https://github.com/blindley/multitext.git"}
